[tool.poetry]
name = "youtube-ml"
version = "0.1.0"
description = ""
authors = ["samyachd <achd.samy@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
plotly = "^6.3.0"
numpy = "^2.3.2"
pandas = "^2.3.2"
ipykernel = "^6.30.1"
seaborn = "^0.13.2"
datetime = "^5.5"
scikit-learn = "^1.7.1"
nbformat = "^5.10.4"
xgboost = "^3.0.4"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.30.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
